import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { ReactQueryProvider } from '@/lib/providers/react-query-provider';
import { ThemeProvider } from '@/lib/providers/theme-provider';
import { Toaster } from '@/components/ui/toaster';
import NextTopLoader from "nextjs-toploader";
import "leaflet/dist/leaflet.css";
import "../globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Reservation app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }> | { locale: string };
}>) {
  const resolvedParams = await Promise.resolve(params)
  const locale = resolvedParams?.locale ?? "en"
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(() => {
  try {
    const storageKey = "ui-theme";
    const root = document.documentElement;
    const savedTheme = localStorage.getItem(storageKey);
    root.classList.remove("light", "dark");
    if (savedTheme === "light" || savedTheme === "dark") {
      root.classList.add(savedTheme);
      return;
    }
    root.classList.add("dark");
  } catch {}
})();`,
          }}
        />
      </head>
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} antialiased font-sans`}
      >
        <NextTopLoader color="var(--primary)" height={3} showSpinner={false} />
        <ThemeProvider defaultTheme="dark" storageKey="ui-theme">
          <NextIntlClientProvider messages={messages}>
            <ReactQueryProvider>
              {children}
            </ReactQueryProvider>
            <Toaster />
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
